### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by werunom** [Kirozen/vsce-wordcounter#12]
Of late, vscode keeps showing the notification that `wordcounter` has taken lot of time to load and in this process has stalled other extensions from loading. Thought of bringing it your notice. 

VSCode has created a txt file having some analytics. I am attaching the file. 

[kirozen.wordcounter-unresponsive.cpuprofile.txt](https://github.com/Kirozen/vsce-wordcounter/files/2725760/kirozen.wordcounter-unresponsive.cpuprofile.txt)

Also, vscode pointed to [this link]( https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load) for the details about `cpu-load`

- OS Version: `Linux x64 4.19.13-1-MANJARO`
- VSCode version: `1.30.1`

**Comment by Kirozen** [comment]
I don't have issue, no high cpu on my side
