### ISSUE TITLE
Words counter stuck and not updating

### ISSUE THREAD

**Issue by alexdevero** [Kirozen/vsce-wordcounter#13]
The "Words" counter get stuck sometimes and stops updating the word count. The "Chars" counter still continues to work and correctly register any changes.

Test file (rename the file to `.md` before testing):
[test-file.md.txt](https://github.com/Kirozen/vsce-wordcounter/files/2901160/test-file.md.txt)

Version: 1.32.0-insider
Commit: 393b48d4a5de85b6fa1d2ad0a59588d6715e12ea
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by alexdevero** [comment]
The extension also resets word count during manual text selection.

**Comment by Kirozen** [comment]
I'm using this:
Version : 1.32.1 (user setup)
Validation : 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date : 2019-03-08T00:51:49.278Z
Électron : 3.1.3
Chrome : 66.0.3359.181
Node.js : 10.2.0
V8 : 6.6.346.32
OS : Windows_NT x64 10.0.17134

I don't have any issue.

Do you have a use case or a flow to reproduce your issue on my side?

**Comment by alexdevero** [comment]
Take a look it the first message:
**Test file (rename the file to .md before testing):**

**Comment by alexdevero** [comment]
Here is another file for test (rename it to .md before testing):
[lorem.md.txt](https://github.com/Kirozen/vsce-wordcounter/files/2951769/lorem.md.txt)

**Comment by Kirozen** [comment]
I already tried with the first one without issues. It's why I asked you more details on what you did with this file.
I juste tried with lorem.md, nothing again.
Could you post the list of your activated extensions ? Maybe an incompatibility

**Comment by alexdevero** [comment]
Sure:
aaron-bond.better-comments
alefragnani.Bookmarks
anseki.vscode-color
bierner.color-info
CoenraadS.bracket-pair-colorizer-2
cssho.vscode-svgviewer
EditorConfig.EditorConfig
formulahendry.auto-close-tag
jock.svg
jpoissonnier.vscode-styled-components
kirozen.wordcounter
lafe.contextualduplicate
mgmcdermott.vscode-language-babel
mhmadhamster.postcss-language
mikestead.dotenv
mrmlnc.vscode-csscomb
mrmlnc.vscode-duplicate
OfHumanBondage.react-proptypes-intellisense
PKief.material-icon-theme
robertohuertasm.vscode-icons
ryuta46.multi-command
Shan.code-settings-sync
shinnn.stylelint
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-czech
yzhang.dictionary-completion
zhuangtongfa.Material-theme

**Comment by alexdevero** [comment]
Here is a screen with the second document. Your extension is on the left. I added another word counter extension. That one is on the right.
![Výstřižek](https://user-images.githubusercontent.com/4237724/54118758-1a125100-43f4-11e9-8c94-72b6fa9cc3d7.PNG)

**Comment by alexdevero** [comment]
Weird thing is the manual selection. When I start at the top of lorem.md.txt, and reach the `<` on line 110 (`class Cat < Animal`), the counter change from 686 to 470. This happens a number of times through the document.

**Comment by Kirozen** [comment]
Wow it's true I saw it ! totally weird ! I will check

**Comment by alexdevero** [comment]
Great! Well, not great in general, but great for debugging.

**Comment by Kirozen** [comment]
I published a new version, tell me if it's ok for you

**Comment by alexdevero** [comment]
It looks like it works. I will do some more tests and let you if the issue appears again. Thank you very much!
