### ISSUE TITLE
Hyphenated words / contractions counted as two words

### ISSUE THREAD

**Issue by nickynicolson** [Kirozen/vsce-wordcounter#14]
The sentence ""Images of x-rays"" is counted as 4 words, most word counting programs (word, `wc` command line utility) would count this as 3.
Similarly: "I won't" and "I will not" are both counted as 3 words, the former should be 2.

**Comment by nickynicolson** [comment]
I think a fix would be to modify this regex (in wordCount method)
https://github.com/Kirozen/vsce-wordcounter/blob/836162fb1dbdd5637a7f5ccd0f28df45636483d4/src/wordCounter.js#L76

...to use a pattern which optionally includes hyphens and apostrophes:
`/\w+([\-']?\w+)*/g`
This pattern would also match multiply contracted words like `fo'c's'le`

**Comment by Kirozen** [comment]
Fixed in v1.6.0
Thanks for your help!
