### ISSUE TITLE
only enable for certain language modes?

### ISSUE THREAD

**Issue by drewda** [Kirozen/vsce-wordcounter#17]
Is it currently possible to selectively enable this extension for certain language modes? I'd like to have it operate on text and Markdown files, but hide on all other languages.

(Thank you for a useful extension!)

**Comment by drewda** [comment]
@Kirozen thanks for this addition!

I'm not able to make it work in my copy of VS Code. I've added the following config:

```json
    "wordcounter.languages": ["plaintext", "markdown"]
```

However, I still see the word count on JSON files, Ruby files, etc. Could you tell me if I got the config wrong?

**Comment by Kirozen** [comment]
Should be ok with v1.8.2

**Comment by drewda** [comment]
Works for me now. Thank you!
