### ISSUE TITLE
Adjusting the word count based on selection

### ISSUE THREAD

**Issue by nickjj** [Kirozen/vsce-wordcounter#2]
Sublime will report back the word count stats based on either the whole document, or the selected text.

What do you think about adding in support so we can get a count report on selected text?

Behavior wise, it could work as is if you don't select anything, but when you select any amount of text, it will report back the stats on just the selected text.

**Comment by Kirozen** [comment]
Good feature :)

**Comment by Kirozen** [comment]
Available in last version : v1.2.0

**Comment by nickjj** [comment]
Excellent, thanks. It's working flawlessly.
