### ISSUE TITLE
Multiple selections count each selection as a separate paragraph

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#21]
Currently, as of version 1.9.2, whenever a multi-selection is done it counts each selection as a different paragraph. For example, if you have 3 selections on a single line, WordCounter counts that as 3 paragraphs. And 3 selections on 3 different lines within the same paragraph, likewise, get counted as 3 paragraphs.

My expectation is that multiple selections within a single paragraph, whether those selections are on the same line or on different lines, should count as 1 paragraph. And multiple selections done across 2 different paragraphs should count as 2 paragraphs, etc.

**Comment by Kirozen** [comment]
I am thinking about it but it's not so easy to implement well

**Comment by Eldaw** [comment]
I understand that this would be very complicated to implement. Maybe the current functionality is OK the way it is. I suppose one could argue that each separate selection should start counting paragraphs and lines from scratch, in which case the counters are currently accurate. If you wish to close this I'll understand.
