### ISSUE TITLE
Multiple blank lines get counted as 1 Line

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#22]
If you start a new empty file and hit Enter a few times to get multiple blank lines, WordCounter 1.9.3 counts only 1 line.

**Comment by Eldaw** [comment]
Same thing if you start pressing Space a few times in a new document (or press the Tab key to automatically make a few spaces). The character counter stays on 0. The spaces are only counted as characters after you start entering text.

**Comment by Kirozen** [comment]
Should be ok with v2.0.0
