### ISSUE TITLE
Feature request: option to count end of line characters as characters

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#26]
It would be nice if there was an option for whether LF and CRLF characters were counted as part of the character count.

**Comment by Kirozen** [comment]
You want an option to remove cr/crlf in character count?

**Comment by Eldaw** [comment]
Yes. Currently the end of line characters are always counted in the character count. I would like an option to disable that.

**Comment by Kirozen** [comment]
Tell me if it's ok for you

**Comment by Eldaw** [comment]
Thanks, it works great!

**Comment by Kirozen** [comment]
What are your needs? It seems you are the most active user of this extension, maybe if I know your usage, I could have new ideas

**Comment by Eldaw** [comment]
For now I can't think of anything else. I'll let you know if I think of any more ideas. For me this is the most useful extension of all and I appreciate your efforts in developing it.
