### ISSUE TITLE
Can't see total word count after selecting then deselecting text

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#27]
Previous reported in https://github.com/Kirozen/vsce-wordcounter/issues/7
and it was fixed at the time.

Unfortunately, this same problem is back again in v2.1.0

_Originally posted by @Eldaw in https://github.com/Kirozen/vsce-wordcounter/issues/7#issuecomment-560384363_

**Comment by Kirozen** [comment]
I noticed it too, I will work on it asap

**Comment by Kirozen** [comment]
Fixed in next release
