### ISSUE TITLE
Quickly selecting a paragraph doesn't always count its words accurately

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#34]
Frequently, I quickly select a paragraph of text to find out how many words are in that paragraph.

With v2.3.0, I've tested this and found that I get inconsistent answers.

With a paragraph that actually contains 104 words, I've found that if I quickly drag select the entire paragraph, I get a different answer each time: e.g. sometimes it tells me 103 words, sometimes 102 words, sometimes 104 words, sometimes 1 word, etc.

Below is a screenshot where I've quickly selected the entire paragraph of 104 words, but I'm being told that it only containts 68 words.

![image](https://user-images.githubusercontent.com/3789849/85285252-7afa5700-b488-11ea-8239-3d6801a83a38.png)

**Comment by Eldaw** [comment]
I've tried lowering the setting wordcounter.throttle.limit to 30 to see if that can solve the problem, but unfortunately that doesn't really make any difference.

Maybe introducing a timer system wasn't quite the right approach. If it was only necessary to solve the problem with changing EOL between CRLF and LF, then I'd rather that the EOL bug come back and this one be solved instead. I tend to do a lot of my writing work in VS Code, and counting words in paragraphs is much more important than being able to immediately see the character count update when changing EOL characters (which is rare).

**Comment by Eldaw** [comment]
Hi @Kirozen I hope all is well. Is development on this extension still continuing?

**Comment by Kirozen** [comment]
Should be better in the new version (2.4.1)

**Comment by Eldaw** [comment]
Has v2.4.1 been published? When I check for extension update in VS Code, the latest is still v2.3.0
