### ISSUE TITLE
Quickly pressing Enter to create new lines causes lines to be counted incorrectly

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#35]
In the example screenshot below, I went to the end of the paragraph and pressed Enter twice, quickly, so that there are now 3 lines in the document.

But I'm being told that there are only 2 lines.

![image](https://user-images.githubusercontent.com/3789849/85286666-f3621780-b48a-11ea-9076-ee9bc8fef69a.png)

**Comment by Kirozen** [comment]
Should be better in the new version (2.4.1)
