### ISSUE TITLE
'0 Word, 0 Char' should read '0 Words, 0 Chars'

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#4]
The text on the status bar updates correctly when going from 1 to 2 (i.e. 'word' to 'words' and 'char' to 'chars'), but for 0 it should be 'Words' and 'Chars'.

**Comment by Eldaw** [comment]
Hi @Kirozen 

Do you think there will be a future version of WordCounter?

**Comment by Kirozen** [comment]
Hi @Eldaw 

Yes, for sure there will be a future version :)

**Comment by Kirozen** [comment]
Done
