### ISSUE TITLE
Fixes for 2 sets of bugs are mutually exclusive

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#47]
It seems there are 2 different sets of bugs. From what I can tell, the fixing of one of these set of bugs causes the other set of bugs. The past several versions have gone back and forth in this manner, fixing and breaking.

**Set 1:**
https://github.com/Kirozen/vsce-wordcounter/issues/3
https://github.com/Kirozen/vsce-wordcounter/issues/33

**Set 2:**
https://github.com/Kirozen/vsce-wordcounter/issues/34
https://github.com/Kirozen/vsce-wordcounter/issues/35

In the current version, v2.4.1, Set 1 is broken. I hope it will be possible somehow to fix Set 1 without breaking Set 2.

**Comment by Kirozen** [comment]
It should be better in 2.4.2 (I hope)
