### ISSUE TITLE
Support multiple selections

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#6]
Reporting stats on selected text using WordCounter is great, however it currently doesn't support multiple selections.

Currently, if you create multiple carets by holding Alt and then clicking in different parts of the text, then hold Shift and use the arrow keys to select a few characters in the multiple locations, WordCounter doesn't recognize that there are multiple selections.

VS Code itself, with it's built-in functionality, shows some stats for the multiple selections on the statusbar though. (e.g. 2 selections, 8 characters selected).

**Comment by Kirozen** [comment]
Available in future release
