### ISSUE TITLE
Can't see total word count after selecting then deselecting text

### ISSUE THREAD

**Issue by Eldaw** [Kirozen/vsce-wordcounter#7]
After selecting some text, if you then click somewhere else in the document to clear the selection, the stats from the previous selection become stuck in the statusbar, i.e. the stats don't get reset to showing the stats for the whole document again.

**Comment by nickjj** [comment]
I notice the same behavior. You have to modify the file in order to see the full document's count again.

**Comment by Kirozen** [comment]
Fixed in future release

**Comment by Eldaw** [comment]
Unfortunately, this same problem is back again in v2.1.0
