### ISSUE TITLE
Wordcounter stops functioning when Spell Right is enabled.

### ISSUE THREAD

**Issue by luetage** [Kirozen/vsce-wordcounter#9]
Hey, I have a weird issue. Whenever I enable [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright), WordCounter stops working. Sometimes I still see the count for selection, at other times nothing. If I disable Spell Right, WordCounter works fine. This started first happening when I tried to enable spellcheck for a document.

**Comment by Kirozen** [comment]
I tested and I don't have issue
